name: Publish Image to Docker Hub
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Set release version environment variable
      # This uses the tag version w/ the "v." removed (this action is only triggered upon a version tag)
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}-amd64" >> $GITHUB_ENV

      - name: Test environment variable
        run: echo ${{ env.RELEASE_VERSION }}

      - name: Check out GitHub repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          # github account and repo name (mikeoertli/ffprobe) match that of docker hub, so we can use the github repo reference here
          tags: ${{ github.repository }}:${{ env.RELEASE_VERSION }}
          file: Dockerfile.amd64
